### ISSUE TITLE
output results format .5 in pos

### ISSUE THREAD

**Issue by masen1991** [cumtr/BAdabouM#2]
Hello 
why the vcf  results pos have .5 ?
such as 
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  BAdabouM_out
1       534326.5        .       N       .       PASS    SVTYPE=INS;END=534326.5;SVLEN=0.0;CIPOS=-43.5,43.5;CIEND=-43.5,43.5     GT      1/1

why POS,END,SVLEN,CIPOS,CIEND all have .5?
does it right?

**Comment by cumtr** [comment]
Dear Masen0407,
Thank you for the report !
This issue should now be solved, I modified the script _BAdabouM_2_vcf.py_.
Let me know if it worked.
